# 00. PyTorch Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.13.0+cu117


In [4]:
!nvidia-smi

Thu Nov 17 14:43:10 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.03    Driver Version: 522.06       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A500...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   50C    P8    18W /  N/A |    830MiB / 16384MiB |     16%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors

### Creating tensors

PyTorch tensors are reated using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9,],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [35]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8568, 0.9473, 0.3403, 0.4247],
        [0.9362, 0.2767, 0.9146, 0.3049],
        [0.7663, 0.7208, 0.6120, 0.2202]])

In [31]:
random_tensor.ndim

3

In [32]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

In [39]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [44]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
# Createing tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [60]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # what datatype is the tensor (e.g. float32, float16)
                              device=None, # What device is your tensor on
                              requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [61]:
float_32_tensor.dtype

torch.float32

In [63]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [64]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [68]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [69]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### GEttign information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [70]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8722, 0.6499, 0.1819, 0.7873],
        [0.2820, 0.9216, 0.9243, 0.6562],
        [0.4100, 0.9337, 0.2754, 0.6856]])

In [72]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor is on: {some_tensor.device}")

tensor([[0.8722, 0.6499, 0.1819, 0.7873],
        [0.2820, 0.9216, 0.9243, 0.6562],
        [0.4100, 0.9337, 0.2754, 0.6856]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [76]:
# Crate a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [77]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [78]:
tensor

tensor([1, 2, 3])

In [79]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [80]:
# Try out PyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [81]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
    
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplicaiton needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3 ,2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [83]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [84]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [86]:
# Matrix multiplication by hand
1 * 1 + 2 *2 + 3 * 3

14

In [87]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
    
print(value)

tensor(14)
CPU times: user 1.37 ms, sys: 256 µs, total: 1.63 ms
Wall time: 995 µs


In [88]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 679 µs, sys: 126 µs, total: 805 µs
Wall time: 530 µs


tensor(14)

### One of the most commeon errors in deep learning: shape errors

In [89]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,5],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8, 11],
                        [9,12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as troch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [90]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [94]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [95]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [98]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 71,  79,  87],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])
